### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by janjanusek** [k2-fsa/sherpa-onnx#1571] opened 2024-11-27 14:46 UTC
Hi there, I found very ugly bug, that no matter which offline transcription model I use appears. 

I split audio into speech segments and try to apply transcription on it after a while RAM consumption explodes from 2GBs up to 8GBs and above 
![image](https://github.com/user-attachments/assets/c8931666-1e8b-4445-9895-ef5bf24aa1d2)
When I dispose model it's all good again so it looks something is gathered in there?. (just a thought)

I'm soon in PROD and this is crucial part so I hope you can find time to check it out as I'm not fluent in C API. 

I'm using latest version of sherpa onnx. Mostly using Zipformer and Moonshine to give you referrence from C# API. Yes, I'm properly disposing stream every time, and no matther count of threads it happens always 
![image](https://github.com/user-attachments/assets/cc26a7f2-f334-45fd-80a5-96da0a2838eb)

**Comment by csukuangfj** [comment] 2024-11-27 15:13
What is the max length among the segments?

**Comment by janjanusek** [comment] 2024-11-27 16:45
Okay you're rigt I'm starting to see very close relationship between max input size and memory consumption. But Why? can I turn it off? At 31 second chunk it was consuming over 3GBs when it was over minute long it jumped to 7.9GB.

Can you explain to me how it works under the hood so I can addapt at least?

**Comment by csukuangfj** [comment] 2024-11-27 17:53
please see our vad + asr example to handle long wave files.


you are not supposed to input long waves to any non-streaming models.

**Comment by csukuangfj** [comment] 2024-11-27 17:55
closing since it is not a bug

**Closed** 2024-11-27 17:55 UTC

**Comment by janjanusek** [comment] 2024-11-28 12:27
But still can you please explain me how it behaves under the hood? I need to fit in 2GBs of RAM and not spend too much time on slow VAD so is there some Buffer pool which loads all that memory or? 

If there is this kind of buffer would it help if I will round the inputs to seconds so there would be at max 30 (1s - 30s) buffers? 

Btw what I'm and not supposed to pass into non streaming models it's not clear from mentioned example and it's not specified in the docs as well.

**Comment by csukuangfj** [comment] 2024-11-28 12:45
I thought it was well known that you would not send long wavs to a non-streaming model due to.memory issue.

**Comment by csukuangfj** [comment] 2024-11-28 12:46
By the way, vad  is super fast that you can ignore the time spent.on it compared with asr.

**Comment by csukuangfj** [comment] 2024-11-28 12:46
If you worry about speed, please measure it first.

**Comment by janjanusek** [comment] 2024-11-28 13:09
Can you at least explain why there is memory issue with offline recognizers or you just don't know?

**Comment by csukuangfj** [comment] 2024-11-28 14:11
It uses attention and I assume you know what attention is and the relationship of the attention matrix  size and the sequence length.

**Comment by janjanusek** [comment] 2024-11-28 14:29
thank you! Now it's clear what I have to do to fix the problem ;)

**Comment by csukuangfj** [comment] 2024-11-28 14:51
> please see our vad + asr example to handle long wave files.
> 
> 
> you are not supposed to input long waves to any non-streaming models.

The solution has already been proposed here. Ues VAD.for.long wavs.
